### ISSUE TITLE
Menu closes right after finger is released

### ISSUE THREAD

**Issue by aerickt** [PeterCxy/evdev-right-click-emulation#3]
I'm running Manjaro Mate on a Dell Venue 11 pro, if that helps. whenever I hold down my finger, the right click is registered, but the moment I release my finger the menu deactivates. Is there a way to mitigate this? Thanks a lot for providing this software which makes Linux on non touch friendly DEs a lot more usable!

**Comment by aerickt** [comment]
I have figured it out lol. To anyone facing my problem, it may be that there are two touch inputs recognized despite being from the same device, so it'll require you to blacklist one of them. Again, thank you so much for this awesome software.

**Comment by kubbur** [comment]
@aerickt how did you blacklist the extra touch input ?

**Comment by horvathcsabalaszlo** [comment]
> @aerickt how did you blacklist the extra touch input ?

https://github.com/PeterCxy/evdev-right-click-emulation
At the bottom, there is the description of environment variables :)
